// <auto-generated />
using System;
using CodeMxBlogsCore.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeMxBlogsCore.Migrations
{
    [DbContext(typeof(BlogsContexto))]
    [Migration("20180803230033_0.0.0.1")]
    partial class _0001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeMxBlogsCore.Modelos.Funcionalidad", b =>
                {
                    b.Property<Guid>("FuncionalidadGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PreRequisitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuncionalidadGuid");

                    b.ToTable("Funcionalidad");
                });

            modelBuilder.Entity("CodeMxBlogsCore.Modelos.Proyecto", b =>
                {
                    b.Property<Guid>("ProyectoGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("UltimaActualizacion");

                    b.HasKey("ProyectoGuid");

                    b.ToTable("Proyecto");
                });

            modelBuilder.Entity("CodeMxBlogsCore.Modelos.Version", b =>
                {
                    b.Property<Guid>("VersionGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caracteristicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("ProyectoGuid");

                    b.Property<Guid?>("ProyectoGuid1");

                    b.HasKey("VersionGuid");

                    b.HasIndex("ProyectoGuid");

                    b.HasIndex("ProyectoGuid1");

                    b.ToTable("Version");
                });

            modelBuilder.Entity("CodeMxBlogsCore.Modelos.Version", b =>
                {
                    b.HasOne("CodeMxBlogsCore.Modelos.Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CodeMxBlogsCore.Modelos.Proyecto", "Proyecto")
                        .WithMany("Versiones")
                        .HasForeignKey("ProyectoGuid1");
                });
#pragma warning restore 612, 618
        }
    }
}
